### PR TITLE
fix docker examples

### PR DESCRIPTION
**Pull request by philliprlittle**

### CODE REVIEW

**Comment by rmuolic** [comment]
Hi @philliprlittle , does this update apply to the all adapters or just OPC UA? If it applies to all adapters, then I'll create another PR in the adapter framework repo for this change. Also, which version/s of the adapter framework does this change apply to?

**Comment by philliprlittle** [comment]
This applies to all adapters. I already have an individual doc PR for each adapter. This applies to the current version of the adapter Framework.

> Hi @philliprlittle , does this update apply to the all adapters or just OPC UA? If it applies to all adapters, then I'll create another PR in the adapter framework repo for this change. Also, which version/s of the adapter framework does this change apply to?

**Review by rmuolic — APPROVED** [review]

**Comment by rmuolic** [comment]
@philliprlittle Feel free to merge.

**Comment by philliprlittle** [comment]
> 

I do not have write access to this repo so I cannot merge

**Comment by KNyce71** [comment]
No worries @philliprlittle , I will merge this later this afternoon. 

cc: @rmuolic

**Review by KNyce71 — APPROVED** [review]

**Pull request merged**
